version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/python:latest-node

    steps:
      - checkout
      - run:
          name: Build Docusaurus Static Page
          command: yarn install && yarn run build
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync ./build/ s3://steven-rutherford.com/

workflows:
  version: 2
  build:
    jobs:
      - deploy-website