version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/python:latest-node

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bb:9c:c0:ac:0d:f2:de:d8:b9:62:4f:4d:6c:84:a3:1e"
      - run:
          name: Clone codersuk repository
          command: >-
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
            git clone git@github.com:StevenR152/CodersUK-Website.git ~/CodersUK-Website
      - run: 
          name: Copy Coders Exercises
          command: cp -r ~/CodersUK-Website/docs ~/project/
      - run:
          name: Build Docusaurus Static Page
          command: yarn install && yarn run build
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync ./build/ s3://steven-rutherford.com/

workflows:
  version: 2
  build:
    jobs:
      - deploy-website